import {
  add,
  addCircleOutline,
  airplaneOutline,
  bagHandleOutline,
  banOutline,
  bedOutline,
  beerOutline,
  bicycleOutline,
  boatOutline,
  bookOutline,
  busOutline,
  businessOutline,
  cafeOutline,
  cameraOutline,
  cardOutline,
  carOutline,
  cartOutline,
  cashOutline,
  checkmarkCircle,
  chevronBack,
  chevronForward,
  close,
  cloudOutline,
  cloudUploadOutline,
  colorPaletteOutline,
  constructOutline,
  cutOutline,
  ellipseOutline,
  ellipsisHorizontalCircleOutline,
  fastFoodOutline,
  filmOutline,
  fitnessOutline,
  flashOutline,
  gameControllerOutline,
  giftOutline,
  globeOutline,
  hammerOutline,
  happyOutline,
  hardwareChipOutline,
  heartOutline,
  homeOutline,
  informationCircleOutline,
  laptopOutline,
  leafOutline,
  medicalOutline,
  moonOutline,
  musicalNotesOutline,
  openOutline,
  pawOutline,
  peopleOutline,
  personOutline,
  phonePortraitOutline,
  pricetagOutline,
  restaurantOutline,
  schoolOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  shirtOutline,
  sparklesOutline,
  starOutline,
  sunnyOutline,
  ticketOutline,
  timeOutline,
  trainOutline,
  umbrellaOutline,
  walletOutline,
  warningOutline,
  waterOutline,
  wifiOutline,
  wineOutline,
} from "ionicons/icons";

const icons = {
  add,
  "add-circle-outline": addCircleOutline,
  "airplane-outline": airplaneOutline,
  "bag-handle-outline": bagHandleOutline,
  "ban-outline": banOutline,
  "bed-outline": bedOutline,
  "beer-outline": beerOutline,
  "bicycle-outline": bicycleOutline,
  "boat-outline": boatOutline,
  "book-outline": bookOutline,
  "bus-outline": busOutline,
  "business-outline": businessOutline,
  "cafe-outline": cafeOutline,
  "camera-outline": cameraOutline,
  "card-outline": cardOutline,
  "car-outline": carOutline,
  "cart-outline": cartOutline,
  "cash-outline": cashOutline,
  "checkmark-circle": checkmarkCircle,
  "chevron-back": chevronBack,
  "chevron-forward": chevronForward,
  close,
  "cloud-outline": cloudOutline,
  "cloud-upload-outline": cloudUploadOutline,
  "color-palette-outline": colorPaletteOutline,
  "construct-outline": constructOutline,
  "cut-outline": cutOutline,
  "ellipse-outline": ellipseOutline,
  "ellipsis-horizontal-circle-outline": ellipsisHorizontalCircleOutline,
  "fast-food-outline": fastFoodOutline,
  "film-outline": filmOutline,
  "fitness-outline": fitnessOutline,
  "flash-outline": flashOutline,
  "game-controller-outline": gameControllerOutline,
  "gift-outline": giftOutline,
  "globe-outline": globeOutline,
  "hammer-outline": hammerOutline,
  "happy-outline": happyOutline,
  "hardware-chip-outline": hardwareChipOutline,
  "heart-outline": heartOutline,
  "home-outline": homeOutline,
  "information-circle-outline": informationCircleOutline,
  "laptop-outline": laptopOutline,
  "leaf-outline": leafOutline,
  "medical-outline": medicalOutline,
  "moon-outline": moonOutline,
  "musical-notes-outline": musicalNotesOutline,
  "open-outline": openOutline,
  "paw-outline": pawOutline,
  "people-outline": peopleOutline,
  "person-outline": personOutline,
  "phone-portrait-outline": phonePortraitOutline,
  "pricetag-outline": pricetagOutline,
  "restaurant-outline": restaurantOutline,
  "school-outline": schoolOutline,
  "settings-outline": settingsOutline,
  "shield-checkmark-outline": shieldCheckmarkOutline,
  "shirt-outline": shirtOutline,
  "sparkles-outline": sparklesOutline,
  "star-outline": starOutline,
  "sunny-outline": sunnyOutline,
  "ticket-outline": ticketOutline,
  "time-outline": timeOutline,
  "train-outline": trainOutline,
  "umbrella-outline": umbrellaOutline,
  "wallet-outline": walletOutline,
  "warning-outline": warningOutline,
  "water-outline": waterOutline,
  "wifi-outline": wifiOutline,
  "wine-outline": wineOutline,
} as const;

export type IoniconName = keyof typeof icons;

function maskSource(source: string) {
  return source
    .replaceAll(
      "class='ionicon-fill-none ionicon-stroke-width'",
      "fill='none' stroke='black' stroke-width='32'",
    )
    .replaceAll("class='ionicon-fill-none'", "fill='none' stroke='black'")
    .replaceAll("class='ionicon-stroke-width'", "stroke-width='32'");
}

export default function Ionicon({
  name,
  size,
  className = "",
}: {
  name: IoniconName;
  size?: number;
  className?: string;
}) {
  const maskImage = `url("${maskSource(icons[name])}")`;
  return (
    <span
      aria-hidden="true"
      className={`ionicon ${className}`.trim()}
      data-ionicon={name}
      style={{
        backgroundColor: "currentColor",
        fontSize: size ? `${size}px` : undefined,
        maskImage,
        WebkitMaskImage: maskImage,
      }}
    />
  );
}
